CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    section_code VARCHAR(255) NOT NULL,
    instructor VARCHAR(255),
    location VARCHAR(255),
    modality VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sections_courses
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
);

CREATE TABLE section_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_section_meetings_sections
        FOREIGN KEY (section_id)
        REFERENCES sections (id)
);

CREATE TABLE availability_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    block_type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE schedule_preferences (
    id BIGINT PRIMARY KEY,
    avoid_early_morning BOOLEAN NOT NULL,
    avoid_late_evening BOOLEAN NOT NULL,
    prefer_compact_schedule BOOLEAN NOT NULL,
    prefer_no_friday_classes BOOLEAN NOT NULL,
    max_classes_per_day INTEGER NOT NULL,
    minimum_gap_minutes INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_schedule_preferences_max_classes_per_day
        CHECK (max_classes_per_day >= 1),
    CONSTRAINT chk_schedule_preferences_minimum_gap_minutes
        CHECK (minimum_gap_minutes >= 0)
);

CREATE TABLE saved_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    preferred BOOLEAN NOT NULL,
    score_total INTEGER NOT NULL,
    preference_penalty INTEGER NOT NULL,
    compactness_score INTEGER NOT NULL,
    gap_score INTEGER NOT NULL,
    max_classes_penalty INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE saved_schedule_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_schedule_id BIGINT NOT NULL,
    course_id BIGINT,
    course_code VARCHAR(255) NOT NULL,
    course_name VARCHAR(255) NOT NULL,
    section_id BIGINT,
    section_code VARCHAR(255) NOT NULL,
    instructor VARCHAR(255),
    location VARCHAR(255),
    modality VARCHAR(255) NOT NULL,
    CONSTRAINT fk_saved_schedule_sections_saved_schedules
        FOREIGN KEY (saved_schedule_id)
        REFERENCES saved_schedules (id)
);

CREATE TABLE saved_schedule_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_schedule_section_id BIGINT NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_saved_schedule_meetings_saved_schedule_sections
        FOREIGN KEY (saved_schedule_section_id)
        REFERENCES saved_schedule_sections (id)
);
